baseURL: https://fauzanelka.id
languageCode: en-us
title: fauzanelka
description: Web development, programming and devops blog.
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
menu:
  main:
    - name: About
      url: about
      weight: 2
    - name: Blog
      url: blog/
      weight: 1
taxonomies:
  series: series
  tags:
params:
  env: production
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  homeInfoParams:
    Title: >
      - Hi 👋 

      - I'm Fauzan.
    Content: >
      - I'm a software development engineer.

      - Welcome to my blog!
  socialIcons:
    - name: github
      url: https://github.com/fauzanelka
    - name: telegram
      url: https://t.me/fauzanelka
    - name: linkedin
      url: https://www.linkedin.com/in/fauzanelka/