baseURL: https://fauzanelka.id
languageCode: en-us
title: fauzanelka
description: Web development, programming and devops blog.
theme: PaperMod
enableRobotsTXT: true
enableEmoji: true
params:
  env: production
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  homeInfoParams:
    Title: >
      - Hi 👋 

      - I'm Fauzan Elka.
    Content: >
      - I'm a software development engineer.

      - Welcome to my blog!
  socialIcons:
    - name: github
      url: https://github.com/fauzanelka
    - name: telegram
      url: https://t.me/fauzanelka
    - name: linkedin
      url: https://www.linkedin.com/in/fauzanelka/